[project]
name = "nest-client"
version = "0.2.0b3"
description = "A Python-based client for the NEST Server"
readme = "README.md"
requires-python = ">=3.10"
license-files = ["LICENSE"]
authors = [
  {name = "Dennis Terhorst"},
  {name = "Jochen M. Eppler"},
  {name = "Sebastian Spreizer"},
]
maintainers = [
  {name = "Dennis Terhorst", email = "d.terhorst@fz-juelich.de"}
]
# keywords = ["NEST", "simulation", "client"]
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",

  # Indicate who your project is intended for
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",

  "Topic :: Education",
  "Topic :: Scientific/Engineering",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "requests>=2.34",
  "werkzeug>=3.1",
]

[project.urls]
homepage = "https://nest-simulator.org"
repository = "https://github.com/nest/nest-client"
documentation = "https://nest-simulator.readthedocs.io"

[project.optional-dependencies]
server = [
  "nest-server>=3.0.0b4",
]

[dependency-groups]
dev = [
  "coverage>=7.16",
  "pre-commit>=4.6",
  "pytest>=9.1",
  "ruff>=0.16",
  "ty>=0.0",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.14
target-version = "py314"

[tool.ruff.lint]
extend-select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ty.environment]
python-version = "3.14"

[tool.ty.rules]
unresolved-attribute = "ignore"
unresolved-import = "ignore"
